### ISSUE TITLE
Rename entrypoint to json2email?

### ISSUE THREAD

**Issue by prologic** [sanger-pathogens/json2email#6]
This is a very cool project. How abut a slightly shorter entrypoint name of ``json2email``?

**Comment by bewt85** [comment]
@prologic, thats a great idea.  I'll see how long it will take to change because I've moved onto something else at work

**Comment by bewt85** [comment]
That took longer than I thought.  So I've renamed the project in github, changed the code and created a new project in pypi.  I've also pushed [a branch](https://github.com/bewt85/jsontoemail/tree/DEPRECATED) to the old jsontoemail project so that (a) it says on [PyPi](https://testpypi.python.org/pypi/jsontoemail/0.0.5) that there won't be any updates and (b) if someone auto-updated and tried to run the script it will either tell them on the command line that they should upgrade or send them an email saying so.

Oh and I changed all the places we use it (nearly forgot that bit).

Anything else you can think I should do?
